spring:
  application:
    name: eureka-center-server
  cloud:
    inetutils:
      preferred-networks: ${PREFERRED_NETWORKS}
  output:
    ansi:
      enabled: always
security:
  basic:
    enabled: true     # 开启基于HTTP basic的认证
  user:
    name: ${SECURITY_NAME}
    password: ${SECURITY_PASSWORD}
---
spring:
  profiles: docker1
server:
  port: ${PORT}
eureka:
  instance:
    hostname: docker-eureka1
    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAL_INSECONDS}
#    prefer-ip-address: true
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
  server:
    enable-self-preservation: false
---
spring:
  profiles: docker2
server:
  port: ${PORT}
eureka:
  instance:
    hostname: docker-eureka2
    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAL_INSECONDS}
#    prefer-ip-address: true
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
  server:
    enable-self-preservation: false
---
spring:
  profiles: docker3
server:
  port: ${PORT}
eureka:
  instance:
    hostname: docker-eureka3
    leaseRenewalIntervalInSeconds: ${LEASE_RENEWAL_INTERVAL_INSECONDS}
#    prefer-ip-address: true
    instance-id: ${HOSTNAME:}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: ${ADDITIONAL_EUREKA_SERVER_LIST}
  server:
    enable-self-preservation: false